# version: '3.8'

# services:
#   frontend:
#     image: jihoovt/crescendo-frontend:20240918112950
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     env_file:
#       - frontend.env
#     networks:
#       - internal_network


#   backend:
#     image: jihoovt/crescendo-backend:20240918112950
#     ports:
#       - "8080:8080"
#     environment:
#       - NODE_ENV=production
#     command: npm run start:prod
#     depends_on:
#       - database
#     env_file:
#       - backend.env
#     volumes:
#       - /home/sangwonlee/cert:/app/cert
#     networks:
#       - internal_network

#   database:
#     image: mongo:latest
#     command: mongod --bind_ip_all
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#       - ./database/init-scripts:/docker-entrypoint-initdb.d
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=kevjayjeong906
#       - MONGO_INITDB_ROOT_PASSWORD=crescendodbuser-1
#     networks:
#       - internal_network

# networks:
#   internal_network:
#     driver: bridge

# volumes:
#   mongo-data:
