const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/auth');
const courseController = require('../controllers/courseController');

router.post('/create', courseController.createCourse);
router.post('/register', courseController.register);
router.get('/', courseController.getCourses);
router.get('/:courseId', courseController.getCourse);
router.put('/:courseId', courseController.updateCourse);
router.delete('/:courseId', courseController.deleteCourse);
router.get('/user/courses', courseController.getRegisteredCourses); 
router.get('/:courseId/students', courseController.getStudentsInCourse);
router.delete('/:courseId/students/:studentId', courseController.deleteStudentFromCourse);
router.post('/:courseId/createGroups', courseController.createGroups);
router.get('/:courseId/groups', courseController.getGroups);
router.post('/:courseId/saveGroups', courseController.saveGroups);
router.post('/:courseId/saveGroup', courseController.saveGroup);
router.delete('/:courseId/groups/:groupId', courseController.deleteGroup);
router.post('/:courseId/addStudent', courseController.addStudentToCourse);
router.post('/:courseId/assignments', courseController.createAssignment);
router.put('/:courseId/assignments/:assignmentId', courseController.updateAssignment);
router.delete('/:courseId/assignments/:assignmentId', courseController.deleteAssignment);
router.get('/', authMiddleware, courseController.getCourses);
router.get('/:courseId', authMiddleware, courseController.getCourse);
router.post('/:courseId/feedbacks', courseController.createFeedback);
router.get('/:courseId/feedbacks', courseController.getFeedbacks);
router.put('/:courseId/feedbacks/:feedbackId', courseController.updateFeedback);
router.delete('/:courseId/feedbacks/:feedbackId', courseController.deleteFeedback);

module.exports = router;
