name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      env:
        NODE_ENV: production
      run: npm run build

    - name: Deploy to server
      run: |
        scp -r ./backend sangwonlee@crescendo.cs.vt.edu:/home/sangwonlee/project_cresendo/deploy_v2/backend
        scp -r ./frontend/build sangwonlee@crescendo.cs.vt.edu:/home/sangwonlee/project_cresendo/deploy_v2/frontend
        ssh sangwonlee@crescendo.cs.vt.edu 'cd /home/sangwonlee/project_cresendo/deploy_v2/backend && npm install && npm run start:prod'
      env:
        NODE_ENV: production
        MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
        CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
        PROFILE_IMAGE: ${{ secrets.PROFILE_IMAGE }}
        SSL_KEY_PATH: ${{ secrets.SSL_KEY_PATH }}
        SSL_CERT_PATH: ${{ secrets.SSL_CERT_PATH }}
        PROD_REDIRECT_URL: ${{ secrets.PROD_REDIRECT_URL }}